sudo: false

branches:
  only:
  - master
  
language: python

before_install:
- openssl aes-256-cbc -K $encrypted_4a5b09341fbf_key -iv $encrypted_4a5b09341fbf_iv -in www-key.enc -out www-key -d
- chmod 400 ~/.ssh/www-key
- echo "Host 2ad.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/ww-key" >> ~/.ssh/config
# replace git@github.com:humrochagf/humrochagf.github.io.git
# for the ssh access of your repository
- git remote set-url origin git@github.com:jac18281828/2ad.com.git
- git fetch origin -f master:master

script:
- (cd 2ad && make html ssh_upload)
