os: linux

branches:
  only:
  - master
  
language: python

before_install:
- openssl aes-256-cbc -K $encrypted_4a5b09341fbf_key -iv $encrypted_4a5b09341fbf_iv -in www-key.enc -out ~/.ssh/www-key -d
- chmod 400 ~/.ssh/www-key
- echo 'Host *' >> ~/.ssh/config
- echo '  IdentitiesOnly=yes' >> ~/.ssh/config
- echo "Host 2ad.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/www-key" >> ~/.ssh/config
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/www-key" >> ~/.ssh/config
- git remote set-url origin git@github.com:jac18281828/2ad.com.git
- git fetch origin -f master:master

install:
- pip install --upgrade pip
- pip install -r requirements.txt

script:
-  make -C 2ad html rsync_upload
-  make -C doc html rsync_upload
-  make -C emmycairns html rsync_upload
-  make -C archiecairns html rsync_upload
-  make -C minacairns html rsync_upload
-  make -C kellycairns html rsync_upload
-  make -C jac html rsync_upload
