FROM jac18281828/tsdev:latest

RUN export DEBIAN_FRONTEND=noninteractive && \
  apt update && \
  apt install -y -q --no-install-recommends \
  build-essential \
  python3 python3-pip ripgrep && \
  apt clean && \
  rm -rf /var/lib/apt/lists/*

ARG PROJECT=2ad.com
WORKDIR /workspace/${PROJECT}

COPY package.json .
RUN yarn install

COPY . .
RUN chown -R jac.jac .
USER jac

RUN yarn prettier:check
RUN yarn lint
RUN yarn build
RUN yarn test
