name: Deploy 2ad.com

on:
  workflow_dispatch:  
  push:
    branches:
      - main
  schedule:
    - cron: '17 4 * * 1'

# at most one deploy at a time      
concurrency:
  group: "www-deploy"
  cancel-in-progress: true
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup rsync (ssh)
      run: |
        mkdir -m 700 -p ${HOME}/.ssh
        ln -f ./.github/scripts/config ${HOME}/.ssh/config
        echo "${WWW_ED25519}" > ${HOME}/.ssh/twoadcom_ed25519
        chmod 400 ${HOME}/.ssh/twoadcom_ed25519
      env:
        WWW_ED25519: ${{ secrets.WWW_ED25519 }}
    - uses: actions/checkout@v2
    - name: Checkout Flex Theme
      uses: actions/checkout@v2
      with:
        repository: alexandrevicenzi/Flex
        path: themes/Flex
    - name: Make Flex Available
      run: |
        ln -sf ${GITHUB_WORKSPACE}/themes 2ad/themes
        ln -sf ${GITHUB_WORKSPACE}/themes kellycairns/themes
    - name: Set up Python 
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
    - name: Build and deploy with make
      run: |
        make -C 2ad html rsync_upload
        make -C emmycairns html rsync_upload
        make -C archiecairns html rsync_upload
        make -C minacairns html rsync_upload
        make -C kellycairns html rsync_upload
