# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Setup rsync
      run:  ./.github/scripts/decrypt_ssh.sh
      env:
        WWW_RSYNC:  ${{ secrets.WWW_RSYNC }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Deploy with make
      run: |
        make -C 2ad html rsync_upload
        make -C doc html rsync_upload
        make -C emmycairns html rsync_upload
        make -C archiecairns html rsync_upload
        make -C minacairns html rsync_upload
        make -C kellycairns html rsync_upload
        make -C jac html rsync_upload
